MVCOnlineTicariOtomasyon/Controllers/CariController.cs
using MVCOnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class CariController : Controller
    {
        // GET: Cari
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler=c.Carilers.Where(x=>x.Durum==true).ToList();

            return View(degerler);
        }

        [HttpGet]
        public ActionResult CariEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CariEkle(Cariler cari)
        {
            c.Carilers.Add(cari);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariSil(int id)
        {
            var ktg = c.Carilers.Find(id);
           ktg.Durum=false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariGetir(int id)
        {
            var Cari = c.Carilers.Find(id);
            return View("CariGetir", Cari);
        }

        public ActionResult CariGuncelle(Cariler k)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var ktgr = c.Carilers.Find(k.Cariid);
            c.Entry(ktgr).CurrentValues.SetValues(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Cariid == id).ToList();
            var cariAd = c.Carilers.Where(x => x.Cariid == id).Select(y=>y.CariAd+ " "+ y.CariSoyad).FirstOrDefault();
            ViewBag.CariAd = cariAd;    
            return View(degerler);
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Cari/CariEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.Siniflar.Cariler

@{
    ViewBag.Title = "CariEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Yeni Cari Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    <br />  

    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    <br />  

    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    <br /> 

    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />  

    <button class="btn btn-info">Kaydet</button>
</form>

MVCOnlineTicariOtomasyon/Views/Cari/CariGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Siniflar.Cariler

@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Güncelleme</h2>
<br />
@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.CariAd)
        @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CariAd, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(x => x.CariSoyad)
        @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CariSoyad, "", new { @style = "color:red" })

        <br />
        @Html.LabelFor(x => x.CariSehir)
        @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.CariMail)
        @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Durum)
        @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
        @Html.HiddenFor(x => x.Cariid)
        <br />
        <button class="btn btn-warning">Güncelle</button>
    </div>


}

MVCOnlineTicariOtomasyon/Views/Cari/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model  List<Cariler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px; ">
    <tr>
        <th>Cari ID</th>
        <th>Cari Adı</th>
        <th>Cari Soyadı</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>

    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <td>@c.Cariid</td>
            <td>@c.CariAd</td>
            <td>@c.CariSoyad</td>
            <td>@c.CariSehir</td>
            <td>@c.CariMail</td>
            <td><a href="/Cari/CariSil/@c.Cariid" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/CariGetir/@c.Cariid" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Cari/MusteriSatis/@c.Cariid" class="btn btn-success">Satış Geçmişi</a></td>
        </tr>
    }

</table>
<a href="/Cari/CariEkle" class="btn btn-info">Cari Ekle</a>

MVCOnlineTicariOtomasyon/Views/Cari/MusteriSatis.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari Adı: @ViewBag.CariAd</li>
</ol>

<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satistid</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="#" class="btn btn-primary">Yazdır</a></td>
        </tr>

    }

</table>